version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=11071726
      - MYSQL_DB=escuela
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 11071726
      MYSQL_DATABASE: escuela
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
